-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 12:39:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `CIF` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `CP` INT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`CIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poyectos` (
  `idPoyectos` INT NOT NULL,
  `FechaIni` DATETIME NULL,
  `FechaFin` DATETIME NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPoyectos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa_tiene_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa_tiene_proyectos` (
  `Empresa_CIF` INT NOT NULL,
  `Poyectos_idPoyectos` INT NOT NULL,
  PRIMARY KEY (`Empresa_CIF`, `Poyectos_idPoyectos`),
  INDEX `fk_Empresa_tiene_proyectos_Poyectos1_idx` (`Poyectos_idPoyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_tiene_proyectos_Empresa`
    FOREIGN KEY (`Empresa_CIF`)
    REFERENCES `mydb`.`Empresa` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_tiene_proyectos_Poyectos1`
    FOREIGN KEY (`Poyectos_idPoyectos`)
    REFERENCES `mydb`.`Poyectos` (`idPoyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `Usuarios_DNI` INT NOT NULL,
  PRIMARY KEY (`Usuarios_DNI`),
  CONSTRAINT `fk_Empleados_Trabajadores1`
    FOREIGN KEY (`Usuarios_DNI`)
    REFERENCES `mydb`.`Usuarios` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados_estan_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados_estan_proyectos` (
  `Poyectos_idPoyectos` INT NOT NULL,
  `Empleados_Trabajadores_DNI` INT NOT NULL,
  `Horas` INT NULL,
  PRIMARY KEY (`Poyectos_idPoyectos`, `Empleados_Trabajadores_DNI`),
  INDEX `fk_Trabajadores_estan_proyectos_Empleados1_idx` (`Empleados_Trabajadores_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajadores_estan_proyectos_Poyectos1`
    FOREIGN KEY (`Poyectos_idPoyectos`)
    REFERENCES `mydb`.`Poyectos` (`idPoyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajadores_estan_proyectos_Empleados1`
    FOREIGN KEY (`Empleados_Trabajadores_DNI`)
    REFERENCES `mydb`.`Empleado` (`Usuarios_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recursos_humanos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recursos_humanos` (
  `Usuarios_DNI` INT NOT NULL,
  PRIMARY KEY (`Usuarios_DNI`),
  CONSTRAINT `fk_Recursos_humanos_Usuarios1`
    FOREIGN KEY (`Usuarios_DNI`)
    REFERENCES `mydb`.`Usuarios` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calendario` (
  `FechaIni` DATETIME NULL,
  `FechaFin` DATETIME NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Estado` CHAR(45) NULL,
  `Empleado_Usuarios_DNI` INT NOT NULL,
  `Recursos_humanos_Usuarios_DNI` INT NOT NULL,
  PRIMARY KEY (`Empleado_Usuarios_DNI`, `Recursos_humanos_Usuarios_DNI`),
  INDEX `fk_Calendario_Empleado1_idx` (`Empleado_Usuarios_DNI` ASC) VISIBLE,
  INDEX `fk_Calendario_Recursos_humanos1_idx` (`Recursos_humanos_Usuarios_DNI` ASC) VISIBLE,
  INDEX `Primario` (`FechaIni` ASC, `FechaFin` ASC, `Empleado_Usuarios_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Calendario_Empleado1`
    FOREIGN KEY (`Empleado_Usuarios_DNI`)
    REFERENCES `mydb`.`Empleado` (`Usuarios_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Recursos_humanos1`
    FOREIGN KEY (`Recursos_humanos_Usuarios_DNI`)
    REFERENCES `mydb`.`Recursos_humanos` (`Usuarios_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
